services:
  app:
    build: 
      context: .
    
    ports:
      - "8000:8000"
    volumes:
      - .:/app       # Volumen para permitir cambios sin reconstruir
      - ./db:/app/db # Persistir la base de datos
    environment:
      - RACK_ENV=development
    
    command: bundle exec rackup -o 0.0.0.0 -p 8000

