
begin
  require 'sinatra/activerecord/rake'
rescue LoadError => e
  puts "No se pudo cargar sinatra/activerecord/rake: #{e}"
end

namespace :db do
  task :load_config do
    require "./app"
  end
end